import assert from 'node:assert/strict';
import test, { before, after } from 'node:test';
import { readFile } from 'node:fs/promises';
import { randomUUID } from 'node:crypto';
import pg from 'pg';
import { PostgresWorkflow } from '../src/workflow/postgres-workflow.js';
const url = process.env.TEST_DATABASE_URL;
const schema = `wf_${randomUUID().replaceAll('-', '')}`;
let admin: pg.Pool, db: pg.Pool, store: PostgresWorkflow;
const owner = {id:'owner',email:'owner@local',role:'owner' as const};
const op = {id:'op',email:'op@local',role:'operator' as const};
const other = {id:'other',email:'other@local',role:'operator' as const};
before(async()=>{if(!url)return; admin=new pg.Pool({connectionString:url}); await admin.query(`CREATE SCHEMA ${schema}`); db=new pg.Pool({connectionString:url,options:`-c search_path=${schema}`}); const sql=await readFile(new URL('../database/schema.sql',import.meta.url),'utf8'); await db.query(sql); await db.query(sql); await db.query("INSERT INTO users(id,email,role,password_hash) VALUES ('owner','owner@local','owner','x'),('op','op@local','operator','x'),('other','other@local','operator','x')"); store=new PostgresWorkflow(db);});
after(async()=>{if(!url)return; await db?.end(); await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end();});
async function fixture(){const id=randomUUID();await db.query("INSERT INTO orders(id,marketplace_order_id,status,processing_deadline) VALUES ($1,$1,'processing',now())",[id]);return String((await db.query("INSERT INTO exceptions(order_id,rule_code,priority,status,reason) VALUES ($1,'EX-01','high','open','late') RETURNING id",[id])).rows[0].id);}
test('concurrent claims permit one winner and preserve one audit', {skip:!url},async()=>{const id=await fixture();const results=await Promise.allSettled([store.claim(op,id,1),store.claim(other,id,1)]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await store.actions(owner,id)).length,1);assert.equal((await store.detail(owner,id)).version,2);});
test('assignment, versions, access, transition and rollback', {skip:!url},async()=>{const id=await fixture();await assert.rejects(store.assign(op,id,'other',1),{status:403});await assert.rejects(store.assign(owner,id,'owner',1),{status:400});let item=await store.assign(owner,id,'op',1);assert.equal(item.version,2);await assert.rejects(store.detail(other,id),{status:403});await assert.rejects(store.transition(op,id,'resolved','done',2),{status:409});item=await store.transition(op,id,'in_progress',null,2);await assert.rejects(store.transition(op,id,'resolved',' ',3),{status:400});item=await store.transition(op,id,'resolved','Completed',3);assert.equal(item.version,4);await assert.rejects(store.assign(owner,id,'other',4),{status:409});assert.equal((await store.actions(owner,id)).length,3);assert.ok(await store.canAccessOrder(op,item.orderId));assert.equal((await store.orderTimeline(op,item.orderId)).exceptions.length,1);});
test('queue filtering, paging and scoped idempotent notification reads', {skip:!url},async()=>{const id=await fixture();assert.ok((await store.list(op,{priority:'high',status:'open',ruleCode:'EX-01',page:1,pageSize:1})).total>=1);assert.equal((await store.operators(owner)).length,2);const n=String((await db.query("INSERT INTO notifications(recipient_id,exception_id,kind,priority,dedupe_key) VALUES ('op',$1,'assignment','high',$2) RETURNING id",[id,randomUUID()])).rows[0].id);assert.equal((await store.notifications(other,{})).total,0);await assert.rejects(store.readNotification(other,n),{status:404});const first=await store.readNotification(op,n);const second=await store.readNotification(op,n);assert.equal(first.readAt,second.readAt);assert.equal((await store.notifications(op,{unreadOnly:true})).total,0);});
